apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: cilium
    version: 1.13.0
    repo: https://helm.cilium.io/
    namespace: kube-system
    valuesFile: values.yaml
    valuesMerge: override
