apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

helmCharts:
  - name: truenas-scale-csi
    version: 0.5.0
    repo: https://terrycain.github.io/truenas-scale-csi/
    namespace: kube-system
    valuesFile: values.yaml
    valuesMerge: override

resources:
  - secret.yaml
