apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: truenas-scale-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-store
  target:
    creationPolicy: Owner
  data:
  - secretKey: token
    remoteRef:
      key: truenas-scale-api
      property: credential
