settings:
  type: "nfs" # either `nfs` or `iscsi`

  # -- TrueNAS API URL, e.g. http://192.168.69.69:1339/api/v2.0
  url: "http://10.24.0.60/api/v2.0"

  # -- TrueNAS dataset path, create a dataset for dynamically provisioned NFS datasets to
  # be stored under. The path is essentially the name of the storage pool and then any datasets
  # in a directory sort of layout. The following command will list all paths:
  #   curl -s -X GET "http://NAS/api/v2.0/pool/dataset" -H "Authorization: Bearer API_TOKEN" | jq '.[].id'
  nfsStoragePath: "main/nfs"

  accessTokenSecretName: truenas-scale-token
