apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./generated.yaml

patches:
- target:
    kind: Namespace
  patch: |-
    $patch: delete
    apiVersion: v1
    kind: Namespace
    metadata:
      name: k0smotron
- target:
    kind: CustomResourceDefinition
    group: apiextensions.k8s.io
    name: clusters.k0smotron.io
  patch: |-
    $patch: delete
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: clusters.k0smotron.io
- target:
    kind: CustomResourceDefinition
    group: apiextensions.k8s.io
    name: jointokenrequests.k0smotron.io
  patch: |-
    $patch: delete
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: jointokenrequests.k0smotron.io
