apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: 1password/connect-sync
    newTag: 1.5.7
  - name: 1password/connect-api
    newTag: 1.5.7
