apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-network
  namespace: default
spec:
  config: |
    {
      "cniVersion":"0.3.1",
      "name":"bridge-netowrk",
      "type":"bridge",
      "bridge":"br0",
      "promiscMode":true,
      "vlan":100,
      "ipam":{}
    }
