apiVersion: v1
kind: PersistentVolume
metadata:
  name: lavender-ceph01
spec:
  storageClassName: manual
  capacity:
    storage: 100G
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Block
  local:
    path: /dev/ubuntu-vg/ceph01
  nodeAffinity:
      required:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - lavender
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: turmeric-ceph01
spec:
  storageClassName: manual
  capacity:
    storage: 60G
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Block
  local:
    path: /dev/ubuntu-vg/ceph01
  nodeAffinity:
      required:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - turmeric
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pepper-ceph01
spec:
  storageClassName: manual
  capacity:
    storage: 60G
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Block
  local:
    path: /dev/ubuntu-vg/ceph01
  nodeAffinity:
      required:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - pepper
