apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - vm.yaml

secretGenerator:
  - name: k8s-nodes-cloud-init
    files:
      - userData=machine.ign
    options:
      disableNameSuffixHash: true
