apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-multus-ds
  namespace: kube-system
spec:
  template:
    spec:
      containers:
      - name: kube-multus
        volumeMounts:
        - mountPath: /host/run
          name: run
          mountPropagation: Bidirectional
      volumes:
      - hostPath:
          path: /run
        name: run
