apiVersion: v1
kind: Namespace
metadata:
  name: amqcache
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: amqcache
  namespace: amqcache
spec:
  replicas: 0
  selector:
    matchLabels:
      app: amqcache
  template:
    metadata:
      labels:
        app: amqcache
    spec:
      containers:
      - name: amqcache
        image: ghcr.io/tsuzu/amqcache:main
        imagePullPolicy: Always
        env:
        - name: AWS_REGION
          value: tsuzu
        - name: AWS_DEFAULT_REGION
          value: tsuzu
        - name: AWS_ROLE_ARN
          value: arn:minio:iam:::role/oxnUw3DAuQF1uggjXGxI2AmW8IA
        - name: AWS_WEB_IDENTITY_TOKEN_FILE
          value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
        - name: AWS_ENDPOINT_URL_STS
          value: http://10.24.0.60:31571
        - name: AWS_ENDPOINT_URL_S3
          value: http://10.24.0.60:31571
        volumeMounts:
        - name: aws-iam-token
          readOnly: true
          mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
      volumes:
      - name: aws-iam-token
        projected:
          sources:
          - serviceAccountToken:
              path: token
              expirationSeconds: 86400
              audience: sts.amazonaws.com
