apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rook-ceph

helmCharts:
  - name: rook-ceph
    version: "v1.17.7"
    repo: https://charts.rook.io/release
    namespace: rook-ceph
    valuesFile: values.yaml
    valuesMerge: override
