apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: epgstation

resources:
  - epgstation.yaml

configMapGenerator:
  - name: litestream-config
    files:
      - litestream.yml
  - name: epgstation-config
    files:
      - config/config.yml
      - config/enc.js
      - config/epgUpdaterLogConfig.yml
      - config/operatorLogConfig.yml
      - config/serviceLogConfig.yml
