apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - projects.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.14.15/manifests/install.yaml

patches:
  - path: argocd-cm.yaml
