apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - https://github.com/miscord-dev/tetrapod/releases/download/v0.0.3/tetrad.yaml
  - secret.yaml

patches:
  - path: daemonset.yaml

configMapGenerator:
  - name: tetrad-config
    files:
      - tetrad.yaml
