apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tetrapod-kubeconfig
  namespace: kube-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-store
  target:
    creationPolicy: Owner
  data:
  - secretKey: kubeconfig
    remoteRef:
      key: tetrapod-control-plane
      property: kubeconfig
