apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://raw.githubusercontent.com/kube-vip/kube-vip-cloud-provider/v0.0.9/manifest/kube-vip-cloud-controller.yaml
- config.yaml
- kubevip-config-controller

patches:
- path: patch.yaml
  target:
    kind: Deployment
    name: kube-vip-cloud-provider
    namespace: kube-system
