env:
  vip_arp: "false"
  bgp_enable: "true"
  vip_interface: br0
  cp_enable: "true"
  vip_cidr: "32"
  lb_enable: "true"
  lb_class_only: "true"
  bgp_as: 64512
  bgp_routerinterface: br0
  bgp_peeraddress: 10.24.0.1
  bgp_peeras: 64512

config:
  address: 10.23.0.1

nodeSelector:
  node-role.kubernetes.io/control-plane: "true"

tolerations:
  - effect: NoExecute
    operator: Exists
  - effect: NoSchedule
    operator: Exists

securityContext:
  capabilities:
    add:
      - NET_ADMIN
      - NET_RAW
      - SYS_TIME
