name: Generate

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: aquaproj/aqua-installer@v3.0.0
        with:
          aqua_version: v2.25.1
      - name: Generate
        run: |
          clusterctl init --bootstrap k0sproject-k0smotron \
                --control-plane k0sproject-k0smotron \
                --infrastructure k0sproject-k0smotron > ./manifests/infra-cluster/cluster-api/generated.yaml
          
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.email "
            git config --global user.name "GitHub Actions"
            git add .
            git commit -m "Update generated manifests"
            git push
          fi
