apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
- cidr-controller.yaml

configMapGenerator:
- name: kubevip-config-controller
  files:
  - controller.mjs
